**1. Series**

In [ ]:
#series is one dimensioanl data structure
import pandas as pd
import numpy as np

sr=pd.Series([1,2,3,4,5,6])
print(type(sr))
print(sr)

#create series from list
sr=pd.Series([1,2,3,4,5,6],
             name="values", index=['001', '002', '003', '004', '005', '006'])
print(sr)

#create series from ndarray
nparr=np.array([1,2,3,4,5,6])
print(type(nparr))
print(nparr)

sr=pd.Series(nparr)
print(sr)

#create serires from dictionary
data = {'a' : 0., 'b' : 1., 'c' : 2.}
print(type(data))
print(data)
s = pd.Series(data)
print(s)

#create serries from scalar
sr=pd.Series(6, index=[0,1,2,3])
print(sr)

<class 'pandas.core.series.Series'>
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
001    1
002    2
003    3
004    4
005    5
006    6
Name: values, dtype: int64
<class 'numpy.ndarray'>
[1 2 3 4 5 6]
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'dict'>
{'a': 0.0, 'b': 1.0, 'c': 2.0}
a    0.0
b    1.0
c    2.0
dtype: float64
0    6
1    6
2    6
3    6
dtype: int64


**2. Series - access data elements**

In [22]:
import pandas as pd
import numpy as np

sr=pd.Series([1,2,3,4,5,6],
             name="values", index=['001', '002', '003', '004', '005', '006'])
print(sr)
print(sr[2:5:1]) # Series[start:stop:step] excluding stop
print(sr[:5])
print(sr[3:])
print(sr[::2])
print(sr[:]) #all elements

for x in sr:
  print(x)

#to take index
print(sr.index)

print(sr.name)
print(sr.shape)
print(sr.size)
print(sr.values)
print(sr.value_counts())

print(sr*2) #arithmatic operation

001    1
002    2
003    3
004    4
005    5
006    6
Name: values, dtype: int64
003    3
004    4
005    5
Name: values, dtype: int64
001    1
002    2
003    3
004    4
005    5
Name: values, dtype: int64
004    4
005    5
006    6
Name: values, dtype: int64
001    1
003    3
005    5
Name: values, dtype: int64
001    1
002    2
003    3
004    4
005    5
006    6
Name: values, dtype: int64
1
2
3
4
5
6
Index(['001', '002', '003', '004', '005', '006'], dtype='object')
values
(6,)
6
[1 2 3 4 5 6]
values
1    1
2    1
3    1
4    1
5    1
6    1
Name: count, dtype: int64
001     2
002     4
003     6
004     8
005    10
006    12
Name: values, dtype: int64


**3. DataFrame creation**

In [42]:
import pandas as pd
from io import StringIO
#create from list
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
print(type(df))
print(df)

df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],
                index=['001', '002', '003'],
                columns=['c1','c2','c3'])
print(df)

#create from dictionary
dt={'c1':[1,2,3], 'c2':[4,5,6], 'c3':[7,8,9]}
df=pd.DataFrame(dt, index=['001', '002', '003'])
print(df)

#create from series
s1=pd.Series([1,2,3])
s2=pd.Series([4,5,6])
s3=pd.Series([7,8,9])
df=pd.DataFrame([s1,s2,s3], index=['001', '002', '003'])
                #columns=['c1','c2','c3'])
print(df)

#create dataframe from ndarray
nparr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(nparr))
print(nparr)

sr=pd.DataFrame(nparr)
print(sr)

#create from csv
df=pd.read_csv("test.csv") #first record is loaded as header or columns
print(df)
print(df.columns)

df=pd.read_csv("test.csv", header=None) #first record is loaded as data
print(df)

#create form JSON
json_data = '''
[
  {"id": 1, "name": "Appu", "age": 25},
  {"id": 2, "name": "Ravi", "age": 30},
  {"id": 3, "name": "Priya", "age": 28}
]
'''
df=pd.read_json(StringIO(json_data))
print(df)


<class 'pandas.core.frame.DataFrame'>
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
     c1  c2  c3
001   1   2   3
002   4   5   6
003   7   8   9
     c1  c2  c3
001   1   4   7
002   2   5   8
003   3   6   9
     0  1  2
001  1  2  3
002  4  5  6
003  7  8  9
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
   1  2  3
0  4  5  6
1  7  8  9
Index(['1', '2', '3'], dtype='object')
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
   id   name  age
0   1   Appu   25
1   2   Ravi   30
2   3  Priya   28


**4. Accessing dataframe elements**

In [58]:
import pandas as pd

#access indexes
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],
                 [11,12,13],[14,15,16],[17,18,19]],
                index=['001', '002', '003', '004', '005', '006'],
                columns=['c1','c2','c3'])
print(df)
print(df.index)

#access columns
print(df.columns)

#get rows - iloc (0-based index), loc(named index)
print(df.iloc[2])
print(df.iloc[1:2])
print(df.iloc[:2])
print(df.iloc[2:])
print(df.iloc[1:5:2])

print(df.loc['002'])
print(type(df.loc['002']))

print(df.loc['002':'004']) #loc includes end index values
print(type(df.loc['002':'004']))

#get data in column wise
print(df['c1']) #singel column
print(df[['c1', 'c3']])  #multiple column

#get rows and columns
print(df.iloc[0:3, 0:2])
print(df.loc['001':'003', 'c1':'c2'])



     c1  c2  c3
001   1   2   3
002   4   5   6
003   7   8   9
004  11  12  13
005  14  15  16
006  17  18  19
Index(['001', '002', '003', '004', '005', '006'], dtype='object')
Index(['c1', 'c2', 'c3'], dtype='object')
c1    7
c2    8
c3    9
Name: 003, dtype: int64
     c1  c2  c3
002   4   5   6
     c1  c2  c3
001   1   2   3
002   4   5   6
     c1  c2  c3
003   7   8   9
004  11  12  13
005  14  15  16
006  17  18  19
     c1  c2  c3
002   4   5   6
004  11  12  13
c1    4
c2    5
c3    6
Name: 002, dtype: int64
<class 'pandas.core.series.Series'>
     c1  c2  c3
002   4   5   6
003   7   8   9
004  11  12  13
<class 'pandas.core.frame.DataFrame'>
001     1
002     4
003     7
004    11
005    14
006    17
Name: c1, dtype: int64
     c1  c3
001   1   3
002   4   6
003   7   9
004  11  13
005  14  16
006  17  19
     c1  c2
001   1   2
002   4   5
003   7   8
     c1  c2
001   1   2
002   4   5
003   7   8


**5. remove rows**

In [73]:
import pandas as pd

#access indexes
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],
                 [11,12,13],[14,15,16],[17,18,19]],
                index=['001', '002', '003', '004', '005', '006'],
                columns=['c1','c2','c3'])
print(df)
print(df.drop('002'))
print(df.drop(['002', '003']))


df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['c1','c2','c3'])
print(df)
print(df.drop(2)) #if there is any label index then we have to pass the label

#to drop based on condition
#print(df.drop([True, False, False, False, False, False])) #this will nto work
print(df[df['c1']>5])

print(df*2) #arithmatic operation


     c1  c2  c3
001   1   2   3
002   4   5   6
003   7   8   9
004  11  12  13
005  14  15  16
006  17  18  19
     c1  c2  c3
001   1   2   3
003   7   8   9
004  11  12  13
005  14  15  16
006  17  18  19
     c1  c2  c3
001   1   2   3
004  11  12  13
005  14  15  16
006  17  18  19
   c1  c2  c3
0   1   2   3
1   4   5   6
2   7   8   9
   c1  c2  c3
0   1   2   3
1   4   5   6
   c1  c2  c3
2   7   8   9
   c1  c2  c3
0   2   4   6
1   8  10  12
2  14  16  18
